web:
  build: .
  command: python3 app.py
  ports:
    - "5001:5000"
  links:
    - db

db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: shortener
  ports:
      - 5435:5432
  restart: always
  volumes:
    - ./db_init:/docker-entrypoint-initdb.d

